import { type ReactNode } from "react";
import { Pressable, StyleSheet, Text, View, type StyleProp, type ViewStyle } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { atlasColors } from "@/constants/atlas";

export function AppPressable({ children, onPress, style, accessibilityLabel }: { children: ReactNode; onPress: () => void; style?: StyleProp<ViewStyle>; accessibilityLabel: string }) { return <Pressable accessibilityRole="button" accessibilityLabel={accessibilityLabel} onPress={onPress} style={({ pressed }) => [styles.pressable, style, pressed && styles.pressed]}>{children}</Pressable>; }
export function Pill({ label, tone = "light" }: { label: string; tone?: "light" | "green" | "sun" | "outline" }) { const toneStyle = tone === "green" ? styles.pillGreen : tone === "sun" ? styles.pillSun : tone === "outline" ? styles.pillOutline : styles.pillLight; return <View style={[styles.pill, toneStyle]}><Text style={tone === "green" ? styles.pillGreenText : styles.pillText}>{label}</Text></View>; }
export function IconCircle({ name, tone = "mint", size = 40 }: { name: React.ComponentProps<typeof MaterialIcons>["name"]; tone?: "mint" | "sun" | "blush" | "ink" | "paper"; size?: number }) { const background = tone === "sun" ? styles.iconSun : tone === "blush" ? styles.iconBlush : tone === "ink" ? styles.iconInk : tone === "paper" ? styles.iconPaper : styles.iconMint; return <View style={[styles.iconCircle, background, { width: size, height: size, borderRadius: size / 2 }]}><MaterialIcons name={name} size={Math.round(size * 0.48)} color={tone === "ink" ? atlasColors.paper : atlasColors.greenDark} /></View>; }
export function ProgressBar({ value, color = "green" }: { value: number; color?: "green" | "sun" | "ink" }) { const fill = color === "sun" ? styles.barSun : color === "ink" ? styles.barInk : styles.barGreen; return <View style={styles.progressTrack} accessibilityRole="progressbar" accessibilityValue={{ min: 0, max: 100, now: value }}><View style={[styles.progressFill, fill, { width: `${value}%` }]} /></View>; }
export function SectionHeading({ eyebrow, title, action }: { eyebrow?: string; title: string; action?: string }) { return <View style={styles.headingRow}><View style={styles.headingCopy}>{eyebrow ? <Text style={styles.eyebrow}>{eyebrow}</Text> : null}<Text style={styles.sectionTitle}>{title}</Text></View>{action ? <Text style={styles.headingAction}>{action}</Text> : null}</View>; }

const styles = StyleSheet.create({
  pressable: { borderRadius: 24 }, pressed: { opacity: 0.76, transform: [{ scale: 0.98 }] }, pill: { alignSelf: "flex-start", borderRadius: 99, paddingHorizontal: 10, paddingVertical: 6 }, pillLight: { backgroundColor: atlasColors.softInk }, pillGreen: { backgroundColor: atlasColors.green }, pillSun: { backgroundColor: "#F7E3BD" }, pillOutline: { backgroundColor: "transparent", borderWidth: 1, borderColor: atlasColors.line }, pillText: { color: atlasColors.greenDark, fontSize: 11, fontWeight: "800", letterSpacing: 0.45 }, pillGreenText: { color: atlasColors.paper, fontSize: 11, fontWeight: "800", letterSpacing: 0.45 },
  iconCircle: { alignItems: "center", justifyContent: "center" }, iconMint: { backgroundColor: atlasColors.mint }, iconSun: { backgroundColor: "#F7E3BD" }, iconBlush: { backgroundColor: atlasColors.blush }, iconInk: { backgroundColor: atlasColors.ink }, iconPaper: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderWidth: 1 },
  progressTrack: { height: 7, backgroundColor: atlasColors.softInk, borderRadius: 99, overflow: "hidden" }, progressFill: { height: "100%", borderRadius: 99 }, barGreen: { backgroundColor: atlasColors.green }, barSun: { backgroundColor: atlasColors.sun }, barInk: { backgroundColor: atlasColors.ink },
  headingRow: { alignItems: "flex-end", flexDirection: "row", justifyContent: "space-between", marginBottom: 12 }, headingCopy: { flex: 1, gap: 3 }, eyebrow: { color: atlasColors.moss, fontSize: 10, fontWeight: "800", letterSpacing: 1.1 }, sectionTitle: { color: atlasColors.ink, fontSize: 21, fontWeight: "800", letterSpacing: -0.45 }, headingAction: { color: atlasColors.green, fontSize: 13, fontWeight: "800" },
});
