import { Modal, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { AtlasScanner } from "@/components/atlas-scanner";
import { AppPressable, IconCircle, Pill, ProgressBar, SectionHeading } from "@/components/atlas-primitives";
import { atlasColors } from "@/constants/atlas";
import { productScores } from "@/lib/atlas-data";
import { useAtlas } from "@/lib/atlas-context";
import { trpc } from "@/lib/trpc";
import { routeAtlasIntent } from "@/lib/atlas-orchestrator";

function CloseButton({ onPress }: { onPress: () => void }) { return <AppPressable accessibilityLabel="Close sheet" onPress={onPress} style={styles.closeButton}><MaterialIcons name="close" size={20} color={atlasColors.ink} /></AppPressable>; }
function SourceEvidence({ sources }: { sources: { id: string; title: string; url: string }[] }) { if (!sources.length) return null; return <View style={styles.evidenceCard}><Text style={styles.evidenceLabel}>SUPPORTING EVIDENCE</Text>{sources.map((source) => <View key={source.id} style={styles.sourceRow}><MaterialIcons name="link" size={16} color={atlasColors.green} /><Text style={styles.sourceText} numberOfLines={1}>{source.title}</Text></View>)}</View>; }

function AISheet() {
  const { aiOpen, closeAI, aiQuery, setAIQuery, aiAnswer, submitAI, addAction } = useAtlas();
  const liveRecommendation = trpc.atlas.ai.recommend.useMutation();
  const handleAsk = () => { const prompt = aiQuery.trim() || "What should I prioritize today?"; submitAI(); liveRecommendation.mutate({ prompt, profileSummary: "Health, financial security, and career are current Atlas priorities. Sensitive connections are not assumed." }); };
  const addToPlan = () => { const action = liveRecommendation.data?.recommendation ?? aiAnswer?.action; if (action) addAction(action, "Atlas AI · cited decision saved"); closeAI(); };
  const hasAnswer = Boolean(aiAnswer || liveRecommendation.data); const route = routeAtlasIntent(aiQuery || "What should I prioritize today?");
  const confidence = liveRecommendation.data?.confidence ?? aiAnswer?.confidence ?? 0;
  const recommendation = liveRecommendation.data?.recommendation ?? aiAnswer?.recommendation ?? "";
  const summary = liveRecommendation.data?.reasoningSummary ?? aiAnswer?.summary ?? "";
  const tradeOff = liveRecommendation.data?.tradeOff ?? aiAnswer?.tradeOff ?? "";
  const factors = liveRecommendation.data?.factors ?? aiAnswer?.factors ?? [];
  return <Modal visible={aiOpen} transparent animationType="slide" onRequestClose={closeAI}><View style={styles.modalRoot}><Pressable style={styles.scrim} onPress={closeAI} accessibilityLabel="Close Atlas AI" /><View style={styles.sheet}>
    <View style={styles.grabber} /><View style={styles.sheetHeader}><View style={styles.identity}><IconCircle name="auto-awesome" tone="ink" size={40} /><View><Text style={styles.sheetEyebrow}>ATLAS AI</Text><Text style={styles.sheetTitle}>Think with your context</Text></View></View><CloseButton onPress={closeAI} /></View>
    <View style={styles.questionBox}><TextInput accessibilityLabel="Ask Atlas AI" value={aiQuery} onChangeText={setAIQuery} placeholder="What should I prioritize today?" placeholderTextColor="#75827A" multiline style={styles.questionInput} /><AppPressable accessibilityLabel="Ask Atlas" onPress={handleAsk} style={styles.askButton}><MaterialIcons name="arrow-upward" size={19} color={atlasColors.paper} /></AppPressable></View>
    {!hasAnswer ? <View style={styles.promptArea}><Text style={styles.promptLabel}>TRY A DECISION</Text>{["Build me a healthy €60 meal plan.", "Can I afford this purchase?", "What should I prioritize today?"].map((prompt) => <AppPressable key={prompt} accessibilityLabel={`Use prompt ${prompt}`} onPress={() => setAIQuery(prompt)} style={styles.promptChip}><Text style={styles.promptText}>{prompt}</Text></AppPressable>)}</View> : <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.answerScroll}>
      <View style={styles.agentRoute}><Pill label={`${route.confidence.toUpperCase()} ROUTE`} tone="outline" /><Text style={styles.agentRouteText}>{route.agent} · {route.rationale}</Text></View><Pill label={`${confidence}% CONFIDENCE`} tone="green" /><Text style={styles.answerEyebrow}>{liveRecommendation.data ? "LIVE ATLAS DECISION" : (aiAnswer?.title ?? "ATLAS DECISION").toUpperCase()}</Text><Text style={styles.answerTitle}>{recommendation}</Text><Text style={styles.answerSummary}>{summary}</Text>
      {liveRecommendation.isPending ? <View style={styles.loadingEvidence}><MaterialIcons name="sync" size={16} color={atlasColors.green} /><Text style={styles.loadingEvidenceText}>Checking the live Atlas provider and evidence…</Text></View> : null}
      <SourceEvidence sources={liveRecommendation.data?.sources ?? []} />
      <View style={styles.factorCard}><Text style={styles.factorTitle}>WHY THIS FITS</Text>{factors.map((factor) => <View key={factor.label} style={styles.factorRow}><Text style={styles.factorLabel}>{factor.label}</Text><View style={styles.factorMeter}><ProgressBar value={factor.score} /></View><Text style={styles.factorScore}>{factor.score}</Text></View>)}</View>
      <View style={styles.tradeOffCard}><MaterialIcons name="balance" size={18} color={atlasColors.terracotta} /><View style={styles.tradeOffCopy}><Text style={styles.tradeOffLabel}>TRADE-OFF</Text><Text style={styles.tradeOffText}>{tradeOff}</Text></View></View>
      <Text style={styles.safetyText}>{liveRecommendation.data?.safetyNote ?? "Atlas provides planning guidance, not medical, legal, or financial advice."}</Text>
      <AppPressable accessibilityLabel="Add Atlas recommendation to plan" onPress={addToPlan} style={styles.primaryAction}><Text style={styles.primaryActionText}>Add to my plan</Text><MaterialIcons name="add" size={19} color={atlasColors.paper} /></AppPressable>
    </ScrollView>}
  </View></View></Modal>;
}

function LensSheet() {
  const { lensOpen, closeLens, lensResult, showLensResult, resetLens, addAction, openScanner, lensBarcode } = useAtlas();
  const liveProduct = trpc.atlas.lens.lookup.useQuery({ barcode: lensBarcode ?? "000000" }, { enabled: Boolean(lensBarcode && lensResult), staleTime: 60_000 });
  const product = liveProduct.data?.product;
  const save = () => { addAction(`Compare ${product?.name ?? "the repairable product option"}`, "Atlas Lens · product intelligence saved"); closeLens(); };
  return <Modal visible={lensOpen} transparent animationType="slide" onRequestClose={closeLens}><View style={styles.modalRoot}><Pressable style={styles.scrim} onPress={closeLens} accessibilityLabel="Close Atlas Lens" /><View style={styles.sheet}>
    <View style={styles.grabber} /><View style={styles.sheetHeader}><View style={styles.identity}><IconCircle name="center-focus-strong" tone="sun" size={40} /><View><Text style={styles.sheetEyebrow}>ATLAS LENS</Text><Text style={styles.sheetTitle}>{lensResult ? "Product intelligence" : "Understand before you buy"}</Text></View></View><CloseButton onPress={closeLens} /></View>
    {!lensResult ? <View style={styles.lensBody}><Text style={styles.lensIntro}>Bring a product into view. Atlas will organize the value, quality, health, and repairability signals you need.</Text><AppPressable accessibilityLabel="Scan barcode" onPress={openScanner} style={styles.lensOption}><IconCircle name="qr-code-scanner" tone="mint" /><View style={styles.lensOptionCopy}><Text style={styles.lensOptionTitle}>Scan barcode</Text><Text style={styles.lensOptionText}>Use your camera for a live product lookup</Text></View><MaterialIcons name="chevron-right" size={22} color={atlasColors.moss} /></AppPressable><AppPressable accessibilityLabel="Take a product photo" onPress={showLensResult} style={styles.lensOption}><IconCircle name="photo-camera" tone="blush" /><View style={styles.lensOptionCopy}><Text style={styles.lensOptionTitle}>Take a photo</Text><Text style={styles.lensOptionText}>Read packaging and materials</Text></View><MaterialIcons name="chevron-right" size={22} color={atlasColors.moss} /></AppPressable><AppPressable accessibilityLabel="Search a product" onPress={showLensResult} style={styles.lensOption}><IconCircle name="search" tone="sun" /><View style={styles.lensOptionCopy}><Text style={styles.lensOptionTitle}>Search manually</Text><Text style={styles.lensOptionText}>Find a product or category</Text></View><MaterialIcons name="chevron-right" size={22} color={atlasColors.moss} /></AppPressable><Text style={styles.lensNote}>Lens analysis is planning guidance. Verify product claims and availability before purchasing.</Text></View> : <ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={styles.answerScroll}>
      <View style={styles.productHero}><View style={styles.productGlyph}><MaterialIcons name="recycling" size={32} color={atlasColors.green} /></View><View style={styles.productCopy}><Text style={styles.productOverline}>{lensBarcode ? `LIVE BARCODE · ${lensBarcode}` : "PRODUCT REVIEW"}</Text><Text style={styles.productName}>{product?.name ?? "Repairable everyday option"}</Text><Text style={styles.productDetails}>{liveProduct.isFetching ? "Looking up live product evidence…" : liveProduct.data?.found ? `${product?.brand ?? "Unknown brand"} · nutrition grade ${product?.nutritionGrade ?? "not reported"}` : "Verified materials · modular design"}</Text></View></View>
      <SourceEvidence sources={liveProduct.data?.sources ?? []} />
      <View style={styles.scoreBanner}><Text style={styles.scoreLabel}>OVERALL SCORE</Text><Text style={styles.scoreValue}>82<Text style={styles.scoreMax}>/100</Text></Text><Pill label="CONSIDER" tone="green" /></View><SectionHeading eyebrow="ATLAS PRODUCT INTELLIGENCE" title="The decision, unpacked" /><View style={styles.scoreGrid}>{productScores.map((score) => <View key={score.label} style={styles.scoreCell}><Text style={styles.scoreCellLabel}>{score.label}</Text><Text style={styles.scoreCellValue}>{score.value}</Text></View>)}</View>
      <View style={styles.tradeOffCard}><MaterialIcons name="thumb-up-alt" size={18} color={atlasColors.green} /><View style={styles.tradeOffCopy}><Text style={styles.tradeOffLabel}>BEST LONG-TERM OPTION</Text><Text style={styles.tradeOffText}>Good durability, repairability, and verified sourcing make this a strong fit.</Text></View></View><View style={styles.compareRow}><Text style={styles.compareLabel}>CHEAPEST ALTERNATIVE</Text><Text style={styles.compareValue}>€15 less today</Text></View><AppPressable accessibilityLabel="Save product decision" onPress={save} style={styles.primaryAction}><Text style={styles.primaryActionText}>Save decision</Text><MaterialIcons name="bookmark-add" size={19} color={atlasColors.paper} /></AppPressable><AppPressable accessibilityLabel="Scan another product" onPress={resetLens} style={styles.secondaryAction}><Text style={styles.secondaryActionText}>Scan another product</Text></AppPressable>
    </ScrollView>}
  </View></View></Modal>;
}
export function AtlasOverlays() { const { openAI } = useAtlas(); return <><AISheet /><LensSheet /><AtlasScanner /><AppPressable accessibilityLabel="Open Atlas AI" onPress={() => openAI()} style={styles.floatingAI}><MaterialIcons name="auto-awesome" size={21} color={atlasColors.paper} /></AppPressable></>; }
const styles = StyleSheet.create({
  modalRoot: { flex: 1, justifyContent: "flex-end" }, scrim: { backgroundColor: "rgba(9,25,19,0.42)", bottom: 0, left: 0, position: "absolute", right: 0, top: 0 }, sheet: { backgroundColor: atlasColors.mist, borderTopLeftRadius: 30, borderTopRightRadius: 30, maxHeight: "90%", minHeight: "64%", paddingBottom: 22, paddingHorizontal: 20 }, grabber: { alignSelf: "center", backgroundColor: "#B6C0B9", borderRadius: 99, height: 5, marginBottom: 13, marginTop: 9, width: 42 }, sheetHeader: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", marginBottom: 17 }, identity: { alignItems: "center", flexDirection: "row", gap: 10 }, sheetEyebrow: { color: atlasColors.moss, fontSize: 10, fontWeight: "900", letterSpacing: 1.15 }, sheetTitle: { color: atlasColors.ink, fontSize: 18, fontWeight: "800", letterSpacing: -0.3, marginTop: 2 }, closeButton: { alignItems: "center", backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 99, borderWidth: 1, height: 38, justifyContent: "center", width: 38 },
  questionBox: { alignItems: "flex-end", backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 8, minHeight: 70, padding: 10 }, questionInput: { color: atlasColors.ink, flex: 1, fontSize: 15, lineHeight: 20, maxHeight: 80, paddingHorizontal: 4, paddingTop: 6 }, askButton: { alignItems: "center", backgroundColor: atlasColors.green, borderRadius: 14, height: 42, justifyContent: "center", width: 42 }, promptArea: { gap: 10, paddingTop: 24 }, promptLabel: { color: atlasColors.moss, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginBottom: 3 }, promptChip: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 14, borderWidth: 1, paddingHorizontal: 14, paddingVertical: 13 }, promptText: { color: atlasColors.ink, fontSize: 14, fontWeight: "700" },
  answerScroll: { gap: 14, paddingBottom: 8 }, agentRoute: { alignItems: "flex-start", backgroundColor: atlasColors.mint, borderRadius: 13, flexDirection: "row", gap: 8, padding: 10 }, agentRouteText: { color: atlasColors.greenDark, flex: 1, fontSize: 11, fontWeight: "700", lineHeight: 16 }, answerEyebrow: { color: atlasColors.moss, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginTop: 2 }, answerTitle: { color: atlasColors.ink, fontSize: 23, fontWeight: "800", letterSpacing: -0.65, lineHeight: 28 }, answerSummary: { color: atlasColors.slate, fontSize: 15, lineHeight: 22 }, factorCard: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 18, borderWidth: 1, gap: 12, padding: 15 }, factorTitle: { color: atlasColors.moss, fontSize: 10, fontWeight: "900", letterSpacing: 1.05 }, factorRow: { alignItems: "center", flexDirection: "row", gap: 9 }, factorLabel: { color: atlasColors.ink, fontSize: 13, fontWeight: "700", width: 100 }, factorMeter: { flex: 1 }, factorScore: { color: atlasColors.green, fontSize: 13, fontWeight: "900", textAlign: "right", width: 22 }, loadingEvidence: { alignItems: "center", backgroundColor: atlasColors.mint, borderRadius: 12, flexDirection: "row", gap: 7, padding: 10 }, loadingEvidenceText: { color: atlasColors.greenDark, fontSize: 12, fontWeight: "700" }, evidenceCard: { backgroundColor: atlasColors.mint, borderRadius: 15, gap: 7, padding: 12 }, evidenceLabel: { color: atlasColors.green, fontSize: 10, fontWeight: "900", letterSpacing: 0.8 }, sourceRow: { alignItems: "center", flexDirection: "row", gap: 7 }, sourceText: { color: atlasColors.greenDark, flex: 1, fontSize: 12, fontWeight: "700" }, tradeOffCard: { alignItems: "flex-start", backgroundColor: atlasColors.blush, borderRadius: 17, flexDirection: "row", gap: 10, padding: 14 }, tradeOffCopy: { flex: 1, gap: 3 }, tradeOffLabel: { color: atlasColors.terracotta, fontSize: 10, fontWeight: "900", letterSpacing: 1.05 }, tradeOffText: { color: atlasColors.ink, fontSize: 13, lineHeight: 19 }, safetyText: { color: atlasColors.moss, fontSize: 11, lineHeight: 16 }, primaryAction: { alignItems: "center", backgroundColor: atlasColors.green, borderRadius: 16, flexDirection: "row", gap: 8, justifyContent: "center", minHeight: 52, paddingHorizontal: 16 }, primaryActionText: { color: atlasColors.paper, fontSize: 15, fontWeight: "800" }, secondaryAction: { alignItems: "center", borderColor: atlasColors.green, borderRadius: 16, borderWidth: 1, justifyContent: "center", minHeight: 49 }, secondaryActionText: { color: atlasColors.green, fontSize: 14, fontWeight: "800" },
  lensBody: { gap: 10 }, lensIntro: { color: atlasColors.slate, fontSize: 15, lineHeight: 22, marginBottom: 7 }, lensOption: { alignItems: "center", backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 12, minHeight: 74, paddingHorizontal: 12 }, lensOptionCopy: { flex: 1, gap: 3 }, lensOptionTitle: { color: atlasColors.ink, fontSize: 15, fontWeight: "800" }, lensOptionText: { color: atlasColors.slate, fontSize: 12 }, lensNote: { color: atlasColors.moss, fontSize: 12, lineHeight: 18, marginTop: 8 }, productHero: { alignItems: "center", backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 19, borderWidth: 1, flexDirection: "row", gap: 13, padding: 14 }, productGlyph: { alignItems: "center", backgroundColor: atlasColors.mint, borderRadius: 16, height: 62, justifyContent: "center", width: 62 }, productCopy: { flex: 1, gap: 3 }, productOverline: { color: atlasColors.moss, fontSize: 9, fontWeight: "900", letterSpacing: 0.95 }, productName: { color: atlasColors.ink, fontSize: 16, fontWeight: "800" }, productDetails: { color: atlasColors.slate, fontSize: 12 }, scoreBanner: { alignItems: "center", backgroundColor: atlasColors.greenDark, borderRadius: 20, flexDirection: "row", justifyContent: "space-between", padding: 16 }, scoreLabel: { color: "#B7D7C9", fontSize: 10, fontWeight: "900", letterSpacing: 1.05, width: 90 }, scoreValue: { color: atlasColors.paper, fontSize: 34, fontWeight: "900", letterSpacing: -1.2 }, scoreMax: { color: "#B7D7C9", fontSize: 14, letterSpacing: 0 }, scoreGrid: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, scoreCell: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 14, borderWidth: 1, width: "31.8%", padding: 11 }, scoreCellLabel: { color: atlasColors.moss, fontSize: 10, fontWeight: "800" }, scoreCellValue: { color: atlasColors.ink, fontSize: 20, fontWeight: "900", marginTop: 3 }, compareRow: { alignItems: "center", borderColor: atlasColors.line, borderRadius: 14, borderWidth: 1, flexDirection: "row", justifyContent: "space-between", padding: 13 }, compareLabel: { color: atlasColors.moss, fontSize: 10, fontWeight: "900", letterSpacing: 0.6 }, compareValue: { color: atlasColors.ink, fontSize: 13, fontWeight: "800" }, floatingAI: { alignItems: "center", backgroundColor: atlasColors.greenDark, borderColor: atlasColors.paper, borderRadius: 99, borderWidth: 3, bottom: 82, elevation: 8, height: 55, justifyContent: "center", position: "absolute", right: 18, shadowColor: "#000", shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.17, shadowRadius: 8, width: 55 },
});
