import { ActivityIndicator, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { AppPressable, IconCircle, Pill } from "@/components/atlas-primitives";
import { atlasColors } from "@/constants/atlas";
import { startOAuthLogin } from "@/constants/oauth";
import { useAuth } from "@/hooks/use-auth";
import { trpc } from "@/lib/trpc";

export function AtlasConnectionCenter() {
  const { isAuthenticated, loading, user } = useAuth();
  const security = trpc.atlas.security.useQuery();
  const catalog = trpc.atlas.connections.catalog.useQuery(undefined, { enabled: isAuthenticated });
  const beginConnection = trpc.atlas.connections.begin.useMutation({ onSuccess: () => catalog.refetch() });
  if (loading) return <View style={styles.loading}><ActivityIndicator color={atlasColors.green} /><Text style={styles.loadingText}>Checking your secure session…</Text></View>;
  if (!isAuthenticated) return <View style={styles.signInCard}><IconCircle name="lock" tone="ink" /><View style={styles.signInCopy}><Text style={styles.signInTitle}>Sign in to unlock connections</Text><Text style={styles.signInText}>Your protected health and financial connection controls are available only in your authenticated Atlas profile.</Text></View><AppPressable accessibilityLabel="Sign in to Atlas" onPress={() => { void startOAuthLogin(); }} style={styles.signInButton}><Text style={styles.signInButtonText}>Sign in</Text><MaterialIcons name="arrow-forward" size={17} color={atlasColors.paper} /></AppPressable></View>;
  return <View style={styles.wrap}>
    <View style={styles.authRow}><View style={styles.authDot} /><Text style={styles.authText}>SIGNED IN AS {user?.name?.toUpperCase() ?? "ATLAS MEMBER"}</Text></View>
    <View style={[styles.guardCard, security.data?.ready ? styles.guardReady : styles.guardBlocked]}><MaterialIcons name={security.data?.ready ? "verified-user" : "lock-outline"} size={18} color={security.data?.ready ? atlasColors.green : atlasColors.terracotta} /><View style={styles.guardCopy}><Text style={styles.guardTitle}>{security.data?.ready ? "Encrypted storage is ready" : "Protected storage is guarded"}</Text><Text style={styles.guardText}>{security.data?.ready ? "Records are encrypted before persistence." : "Development credentials must be updated before any sensitive record can be stored."}</Text></View></View>
    {catalog.data?.providers.map((provider) => <View key={provider.provider} style={styles.providerCard}><IconCircle name={provider.domain === "health" ? "favorite" : "account-balance-wallet"} tone={provider.domain === "health" ? "blush" : "sun"} /><View style={styles.providerCopy}><Text style={styles.providerDomain}>{provider.domain.toUpperCase()} CONNECTION</Text><Text style={styles.providerTitle}>{provider.provider}</Text><Text style={styles.providerText}>{provider.configured ? "Credentials are configured. Review consent to continue." : "Development credentials are not configured yet."}</Text></View><AppPressable accessibilityLabel={`Review ${provider.provider} connection`} onPress={() => { beginConnection.mutate({ domain: provider.domain, provider: provider.provider, purpose: "Build a user-controlled Atlas context", scopes: [...provider.scopes] }); }} style={[styles.providerAction, !provider.configured && styles.providerActionMuted]}><Text style={styles.providerActionText}>{provider.configured ? "Review" : "Set up"}</Text></AppPressable></View>)}
    {beginConnection.data?.status === "blocked" || beginConnection.data?.status === "needs_credentials" ? <View style={styles.statusNote}><Pill label="NOT CONNECTED" tone="outline" /><Text style={styles.statusText}>{beginConnection.data.reason}</Text></View> : null}
  </View>;
}
const styles = StyleSheet.create({
  wrap: { gap: 10 }, loading: { alignItems: "center", backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 10, padding: 14 }, loadingText: { color: atlasColors.slate, fontSize: 13, fontWeight: "700" }, signInCard: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 19, borderWidth: 1, gap: 12, padding: 14 }, signInCopy: { gap: 3 }, signInTitle: { color: atlasColors.ink, fontSize: 15, fontWeight: "800" }, signInText: { color: atlasColors.slate, fontSize: 12, lineHeight: 17 }, signInButton: { alignItems: "center", backgroundColor: atlasColors.green, borderRadius: 13, flexDirection: "row", gap: 7, justifyContent: "center", padding: 12 }, signInButtonText: { color: atlasColors.paper, fontSize: 13, fontWeight: "800" }, authRow: { alignItems: "center", flexDirection: "row", gap: 6 }, authDot: { backgroundColor: atlasColors.green, borderRadius: 99, height: 7, width: 7 }, authText: { color: atlasColors.green, fontSize: 10, fontWeight: "900", letterSpacing: 0.65 }, guardCard: { alignItems: "flex-start", borderRadius: 16, flexDirection: "row", gap: 10, padding: 13 }, guardReady: { backgroundColor: atlasColors.mint }, guardBlocked: { backgroundColor: atlasColors.blush }, guardCopy: { flex: 1, gap: 2 }, guardTitle: { color: atlasColors.ink, fontSize: 13, fontWeight: "800" }, guardText: { color: atlasColors.slate, fontSize: 11, lineHeight: 16 }, providerCard: { alignItems: "center", backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 17, borderWidth: 1, flexDirection: "row", gap: 10, padding: 12 }, providerCopy: { flex: 1, gap: 2 }, providerDomain: { color: atlasColors.moss, fontSize: 9, fontWeight: "900", letterSpacing: 0.85 }, providerTitle: { color: atlasColors.ink, fontSize: 14, fontWeight: "800" }, providerText: { color: atlasColors.slate, fontSize: 10, lineHeight: 14 }, providerAction: { alignItems: "center", backgroundColor: atlasColors.green, borderRadius: 11, justifyContent: "center", minHeight: 34, paddingHorizontal: 10 }, providerActionMuted: { backgroundColor: atlasColors.moss }, providerActionText: { color: atlasColors.paper, fontSize: 11, fontWeight: "800" }, statusNote: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 14, borderWidth: 1, gap: 7, padding: 12 }, statusText: { color: atlasColors.slate, fontSize: 11, lineHeight: 16 },
});
