import { useMemo, useState } from "react";
import { StyleSheet, Text, View } from "react-native";
import { AppPressable, Pill } from "@/components/atlas-primitives";
import { atlasColors } from "@/constants/atlas";
import { useAuth } from "@/hooks/use-auth";
import { applyAtlasBriefNotifications, type AtlasBriefNotificationPreferences } from "@/lib/atlas-brief-notifications";
import { trpc } from "@/lib/trpc";

const defaults: AtlasBriefNotificationPreferences = { dailyEnabled: false, dailyHour: 8, dailyMinute: 0, weeklyEnabled: false, weeklyWeekday: 1, weeklyHour: 9, weeklyMinute: 0, notificationEnabled: false, digestMode: true };
export function AtlasBriefCenter() { const { isAuthenticated } = useAuth(); const preferencesQuery = trpc.atlas.briefs.preferences.useQuery(undefined, { enabled: isAuthenticated, retry: false }); const updatePreferences = trpc.atlas.briefs.updatePreferences.useMutation(); const activateSchedules = trpc.atlas.briefs.activateSchedules.useMutation(); const [local, setLocal] = useState<AtlasBriefNotificationPreferences>(defaults); const [status, setStatus] = useState("Off"); const current = useMemo(() => preferencesQuery.data ? { dailyEnabled: preferencesQuery.data.dailyEnabled, dailyHour: preferencesQuery.data.dailyHour, dailyMinute: preferencesQuery.data.dailyMinute, weeklyEnabled: preferencesQuery.data.weeklyEnabled, weeklyWeekday: preferencesQuery.data.weeklyWeekday, weeklyHour: preferencesQuery.data.weeklyHour, weeklyMinute: preferencesQuery.data.weeklyMinute, notificationEnabled: preferencesQuery.data.notificationEnabled, digestMode: preferencesQuery.data.digestMode } : local, [local, preferencesQuery.data]); const update = async (patch: Partial<AtlasBriefNotificationPreferences>) => { const next = { ...current, ...patch }; setLocal(next); const delivery = await applyAtlasBriefNotifications(next); setStatus(delivery.status === "scheduled" ? `${delivery.count} device reminder${delivery.count === 1 ? "" : "s"} active` : delivery.status === "permission_denied" ? "Notifications need permission" : delivery.status === "web_unsupported" ? "Device reminders are available in the mobile build" : "Off"); if (isAuthenticated) updatePreferences.mutate(next); }; const activate = () => { if (!isAuthenticated) { setStatus("Sign in to enable managed brief generation"); return; } activateSchedules.mutate(current, { onSuccess: (result) => setStatus(result.scheduled ? "Managed brief generation is active" : result.reason ?? "Managed brief scheduling is unavailable"), onError: () => setStatus("Publish Atlas before activating managed brief generation") }); };
  return <View style={styles.card}><View style={styles.top}><View><Text style={styles.eyebrow}>ATLAS BRIEFS</Text><Text style={styles.title}>Daily and weekly rhythm</Text></View><Pill label={isAuthenticated ? "SYNCED" : "DEVICE ONLY"} tone={isAuthenticated ? "green" : "outline"} /></View><Text style={styles.copy}>Choose calm reminders for your personal briefing. Atlas never sends a brief without your permission.</Text><View style={styles.buttons}><AppPressable accessibilityLabel="Toggle daily Atlas brief" onPress={() => void update({ dailyEnabled: !current.dailyEnabled, notificationEnabled: !current.dailyEnabled || current.notificationEnabled })} style={[styles.button, current.dailyEnabled && styles.buttonActive]}><Text style={[styles.buttonText, current.dailyEnabled && styles.buttonTextActive]}>Daily · 08:00</Text></AppPressable><AppPressable accessibilityLabel="Toggle weekly Atlas brief" onPress={() => void update({ weeklyEnabled: !current.weeklyEnabled, notificationEnabled: !current.weeklyEnabled || current.notificationEnabled })} style={[styles.button, current.weeklyEnabled && styles.buttonActive]}><Text style={[styles.buttonText, current.weeklyEnabled && styles.buttonTextActive]}>Weekly · Monday</Text></AppPressable></View>{isAuthenticated ? <AppPressable accessibilityLabel="Activate managed Atlas brief generation" onPress={activate} style={styles.activate}><Text style={styles.activateText}>{activateSchedules.isPending ? "Activating…" : "Activate managed brief generation"}</Text></AppPressable> : null}<Text style={styles.status}>{status}</Text></View>;
}
const styles = StyleSheet.create({ card: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 17, borderWidth: 1, gap: 10, padding: 13 }, top: { alignItems: "flex-start", flexDirection: "row", justifyContent: "space-between" }, eyebrow: { color: atlasColors.moss, fontSize: 9, fontWeight: "900", letterSpacing: 0.7 }, title: { color: atlasColors.ink, fontSize: 15, fontWeight: "800", marginTop: 3 }, copy: { color: atlasColors.slate, fontSize: 11, lineHeight: 16 }, buttons: { flexDirection: "row", gap: 8 }, button: { alignItems: "center", backgroundColor: atlasColors.mist, borderRadius: 10, flex: 1, paddingVertical: 10 }, buttonActive: { backgroundColor: atlasColors.green }, buttonText: { color: atlasColors.moss, fontSize: 11, fontWeight: "800" }, buttonTextActive: { color: atlasColors.paper }, activate: { alignItems: "center", borderColor: atlasColors.green, borderRadius: 10, borderWidth: 1, paddingVertical: 9 }, activateText: { color: atlasColors.green, fontSize: 11, fontWeight: "800" }, status: { color: atlasColors.moss, fontSize: 10, fontWeight: "700" } });
