import { useState } from "react";
import { FlatList, StyleSheet, Text, TextInput, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { AppPressable, Pill } from "@/components/atlas-primitives";
import { atlasColors, atlasPriorityOptions, atlasValueOptions } from "@/constants/atlas";
import { ScreenContainer } from "@/components/screen-container";
import { useAtlas } from "@/lib/atlas-context";

export function AtlasOnboarding() {
  const [step, setStep] = useState(0); const { profile, updateName, togglePriority, toggleValue, completeOnboarding } = useAtlas(); const isFinal = step === 2;
  const title = step === 0 ? "A clearer way\nto move forward." : step === 1 ? "What matters\nmost right now?" : "What should guide\nyour decisions?";
  const body = step === 0 ? "Atlas turns the context you choose to share into practical, considered next steps." : step === 1 ? "Choose more than one. Your priorities shape the intelligence you see first." : "Select the values you want Atlas to protect when trade-offs are involved.";
  const data = step === 1 ? atlasPriorityOptions : atlasValueOptions;
  return <ScreenContainer edges={["top", "bottom", "left", "right"]} containerClassName="bg-background"><View style={styles.page}>
    <View style={styles.brandRow}><View style={styles.brandMark}><MaterialIcons name="public" size={18} color={atlasColors.paper} /></View><Text style={styles.brand}>ATLAS SANCTUM</Text><Text style={styles.step}>0{step + 1} / 03</Text></View>
    <View style={styles.copyBlock}><Pill label={step === 0 ? "YOUR PERSONAL ATLAS" : "PROGRESSIVE SETUP"} tone="sun" /><Text style={styles.title}>{title}</Text><Text style={styles.body}>{body}</Text></View>
    <View style={styles.contentBlock}>{step === 0 ? <View style={styles.identityCard}><Text style={styles.inputLabel}>WHAT SHOULD ATLAS CALL YOU?</Text><TextInput accessibilityLabel="Your name" value={profile.name} onChangeText={updateName} placeholder="Your first name" placeholderTextColor="#7F8D86" style={styles.nameInput} returnKeyType="done" /><View style={styles.privacyRow}><MaterialIcons name="shield" size={18} color={atlasColors.green} /><Text style={styles.privacyText}>You remain in control of what Atlas can access.</Text></View></View> : <FlatList data={data} keyExtractor={(item) => item} numColumns={2} columnWrapperStyle={styles.optionRow} contentContainerStyle={styles.optionList} renderItem={({ item }) => { const selected = step === 1 ? profile.priorities.includes(item) : profile.values.includes(item); return <AppPressable accessibilityLabel={`Toggle ${item}`} onPress={() => step === 1 ? togglePriority(item as (typeof atlasPriorityOptions)[number]) : toggleValue(item as (typeof atlasValueOptions)[number])} style={[styles.option, selected && styles.optionSelected]}><Text style={[styles.optionText, selected && styles.optionTextSelected]}>{item}</Text>{selected ? <MaterialIcons name="check-circle" size={19} color={atlasColors.green} /> : null}</AppPressable>; }} />}</View>
    <View style={styles.footer}><View style={styles.dots}><View style={[styles.dot, step === 0 && styles.dotActive]} /><View style={[styles.dot, step === 1 && styles.dotActive]} /><View style={[styles.dot, step === 2 && styles.dotActive]} /></View><AppPressable accessibilityLabel={isFinal ? "Enter your Atlas" : "Continue"} onPress={() => isFinal ? completeOnboarding() : setStep((previous) => previous + 1)} style={styles.continueButton}><Text style={styles.continueText}>{isFinal ? "Enter your Atlas" : "Continue"}</Text><MaterialIcons name="arrow-forward" size={20} color={atlasColors.paper} /></AppPressable></View>
  </View></ScreenContainer>;
}
const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: atlasColors.mist, paddingHorizontal: 22, paddingVertical: 18 }, brandRow: { alignItems: "center", flexDirection: "row", gap: 8 }, brandMark: { alignItems: "center", backgroundColor: atlasColors.green, borderRadius: 99, height: 30, justifyContent: "center", width: 30 }, brand: { color: atlasColors.ink, flex: 1, fontSize: 11, fontWeight: "900", letterSpacing: 1.5 }, step: { color: atlasColors.moss, fontSize: 11, fontWeight: "800", letterSpacing: 0.7 },
  copyBlock: { gap: 15, marginTop: 48 }, title: { color: atlasColors.ink, fontSize: 36, fontWeight: "800", letterSpacing: -1.5, lineHeight: 41 }, body: { color: atlasColors.slate, fontSize: 16, lineHeight: 24, maxWidth: 330 }, contentBlock: { flex: 1, justifyContent: "center", marginTop: 20 }, identityCard: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 24, borderWidth: 1, gap: 14, padding: 20 }, inputLabel: { color: atlasColors.moss, fontSize: 10, fontWeight: "900", letterSpacing: 1 }, nameInput: { borderBottomColor: atlasColors.line, borderBottomWidth: 1, color: atlasColors.ink, fontSize: 24, fontWeight: "700", paddingBottom: 12, paddingTop: 2 }, privacyRow: { alignItems: "center", flexDirection: "row", gap: 9, marginTop: 4 }, privacyText: { color: atlasColors.slate, flex: 1, fontSize: 13, lineHeight: 18 },
  optionList: { gap: 10 }, optionRow: { gap: 10 }, option: { alignItems: "center", backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 18, borderWidth: 1, flex: 1, flexDirection: "row", justifyContent: "space-between", minHeight: 57, paddingHorizontal: 14 }, optionSelected: { backgroundColor: atlasColors.mint, borderColor: atlasColors.green }, optionText: { color: atlasColors.ink, fontSize: 14, fontWeight: "700", maxWidth: "82%" }, optionTextSelected: { color: atlasColors.greenDark },
  footer: { gap: 16, paddingTop: 12 }, dots: { flexDirection: "row", gap: 6, justifyContent: "center" }, dot: { backgroundColor: "#C9D3CC", borderRadius: 99, height: 6, width: 6 }, dotActive: { backgroundColor: atlasColors.green, width: 22 }, continueButton: { alignItems: "center", backgroundColor: atlasColors.green, borderRadius: 18, flexDirection: "row", justifyContent: "center", minHeight: 56, gap: 9 }, continueText: { color: atlasColors.paper, fontSize: 16, fontWeight: "800" },
});
