import { parse as parseCookie } from "cookie";
import type { Express, Request, Response } from "express";
import { COOKIE_NAME } from "../shared/const";
import * as db from "./db";
import { createHeartbeatJob, updateHeartbeatJob } from "./_core/heartbeat";
import { sdk } from "./_core/sdk";

export type BriefCadence = "daily" | "weekly";
export type BriefPreferenceInput = { dailyEnabled: boolean; dailyHour: number; dailyMinute: number; weeklyEnabled: boolean; weeklyWeekday: number; weeklyHour: number; weeklyMinute: number; notificationEnabled: boolean; digestMode: boolean };
export const defaultBriefPreferences: BriefPreferenceInput = { dailyEnabled: false, dailyHour: 8, dailyMinute: 0, weeklyEnabled: false, weeklyWeekday: 1, weeklyHour: 9, weeklyMinute: 0, notificationEnabled: false, digestMode: true };
export function toCron(cadence: BriefCadence, input: BriefPreferenceInput) { return cadence === "daily" ? `0 ${input.dailyMinute} ${input.dailyHour} * * *` : `0 ${input.weeklyMinute} ${input.weeklyHour} * * ${input.weeklyWeekday}`; }
export function activeCadences(input: BriefPreferenceInput): BriefCadence[] { return ([input.dailyEnabled && "daily", input.weeklyEnabled && "weekly"].filter(Boolean) as BriefCadence[]); }
export function normalizeBriefPreferences(input: Partial<BriefPreferenceInput>): BriefPreferenceInput { const merged = { ...defaultBriefPreferences, ...input }; if (merged.dailyHour < 0 || merged.dailyHour > 23 || merged.weeklyHour < 0 || merged.weeklyHour > 23) throw new Error("Brief hours must be between 0 and 23"); if (merged.dailyMinute < 0 || merged.dailyMinute > 59 || merged.weeklyMinute < 0 || merged.weeklyMinute > 59) throw new Error("Brief minutes must be between 0 and 59"); if (merged.weeklyWeekday < 0 || merged.weeklyWeekday > 6) throw new Error("Weekly brief weekday must be between 0 and 6"); return merged; }
export async function reconcileBriefSchedules(req: Request, userId: number, preferences: BriefPreferenceInput, existing: { dailyTaskUid: string | null; weeklyTaskUid: string | null } | null) { const session = parseCookie(req.headers.cookie ?? "")[COOKIE_NAME] ?? ""; if (!session) return { scheduled: false, reason: "Sign in again before Atlas can create managed brief schedules." }; const results: Array<{ cadence: BriefCadence; taskUid?: string; nextExecutionAt?: string | null }> = []; for (const cadence of activeCadences(preferences)) { const taskUid = cadence === "daily" ? existing?.dailyTaskUid : existing?.weeklyTaskUid; const cron = toCron(cadence, preferences); if (taskUid) { const updated = await updateHeartbeatJob(taskUid, { cron, enable: true, description: `Atlas ${cadence} brief` }, session); results.push({ cadence, taskUid, ...updated }); } else { const created = await createHeartbeatJob({ name: `atlas-brief-${cadence}-${userId}`, cron, path: "/api/scheduled/atlas-brief", payload: { cadence }, description: `Atlas ${cadence} brief` }, session); await db.updateAtlasBriefTask(userId, cadence, created.taskUid); results.push({ cadence, ...created }); } } return { scheduled: true, jobs: results }; }
export function registerAtlasBriefRoutes(app: Express) { app.post("/api/scheduled/atlas-brief", async (req: Request, res: Response) => { try { const user = await sdk.authenticateRequest(req); if (!user.isCron || !user.taskUid) return res.status(403).json({ error: "cron-only" }); const preference = await db.findAtlasBriefPreferenceByTask(user.taskUid); if (!preference) return res.json({ ok: true, skipped: "orphan" }); const cadence: BriefCadence = preference.dailyTaskUid === user.taskUid ? "daily" : "weekly"; const enabled = cadence === "daily" ? preference.dailyEnabled : preference.weeklyEnabled; if (!enabled) return res.json({ ok: true, skipped: "paused" }); const snapshot = await db.getAtlasLifeSnapshot(preference.userId); const details = snapshot ? "Your saved Atlas context is ready for review." : "Open Atlas to prepare your personal context."; await db.createAtlasBriefRecord(preference.userId, cadence, `${cadence === "daily" ? "Daily" : "Weekly"} Atlas brief: ${details}`); return res.json({ ok: true, cadence, createdAt: new Date().toISOString() }); } catch (error) { return res.status(500).json({ error: error instanceof Error ? error.message : "brief generation failed", timestamp: new Date().toISOString() }); } }); }
