import { and, desc, eq } from "drizzle-orm";
import { drizzle } from "drizzle-orm/mysql2";
import { atlasBriefPreferences, atlasBriefRecords, atlasConnections, atlasConsents, atlasLifeSnapshots, atlasSensitiveRecords, type InsertAtlasConnection, type InsertAtlasConsent, type InsertAtlasSensitiveRecord, type InsertUser, users } from "../drizzle/schema";
import { ENV } from "./_core/env";

let _db: ReturnType<typeof drizzle> | null = null;
export async function getDb() { if (!_db && process.env.DATABASE_URL) { try { _db = drizzle(process.env.DATABASE_URL); } catch { _db = null; } } return _db; }
export async function upsertUser(user: InsertUser): Promise<void> { if (!user.openId) throw new Error("User openId is required for upsert"); const db = await getDb(); if (!db) return; const values: InsertUser = { ...user, role: user.role ?? (user.openId === ENV.ownerOpenId ? "admin" : "user"), lastSignedIn: user.lastSignedIn ?? new Date() }; await db.insert(users).values(values).onDuplicateKeyUpdate({ set: { name: values.name ?? null, email: values.email ?? null, loginMethod: values.loginMethod ?? null, lastSignedIn: new Date() } }); }
export async function getUserByOpenId(openId: string) { const db = await getDb(); if (!db) return undefined; return (await db.select().from(users).where(eq(users.openId, openId)).limit(1))[0]; }
export async function listAtlasConnections(userId: number) { const db = await getDb(); if (!db) return []; return db.select().from(atlasConnections).where(eq(atlasConnections.userId, userId)).orderBy(desc(atlasConnections.updatedAt)); }
export async function createAtlasConsent(input: InsertAtlasConsent) { const db = await getDb(); if (!db) return false; await db.insert(atlasConsents).values(input); return true; }
export async function createAtlasConnection(input: InsertAtlasConnection) { const db = await getDb(); if (!db) return false; await db.insert(atlasConnections).values(input); return true; }
export async function createAtlasSensitiveRecord(input: InsertAtlasSensitiveRecord) { const db = await getDb(); if (!db) return false; await db.insert(atlasSensitiveRecords).values(input); return true; }
export async function getAtlasLifeSnapshot(userId: number) { const db = await getDb(); if (!db) return null; return (await db.select().from(atlasLifeSnapshots).where(eq(atlasLifeSnapshots.userId, userId)).orderBy(desc(atlasLifeSnapshots.updatedAt)).limit(1))[0] ?? null; }
export async function saveAtlasLifeSnapshot(userId: number, payloadJson: string) { const db = await getDb(); if (!db) return { persisted: false as const }; const existing = await getAtlasLifeSnapshot(userId); if (existing) { await db.update(atlasLifeSnapshots).set({ payloadJson, version: "v1" }).where(and(eq(atlasLifeSnapshots.id, existing.id), eq(atlasLifeSnapshots.userId, userId))); return { persisted: true as const, updatedAt: new Date().toISOString() }; } await db.insert(atlasLifeSnapshots).values({ userId, payloadJson, version: "v1" }); return { persisted: true as const, updatedAt: new Date().toISOString() }; }
export async function getAtlasBriefPreferences(userId: number) { const db = await getDb(); if (!db) return null; return (await db.select().from(atlasBriefPreferences).where(eq(atlasBriefPreferences.userId, userId)).limit(1))[0] ?? null; }
export async function saveAtlasBriefPreferences(userId: number, values: Partial<Omit<typeof atlasBriefPreferences.$inferInsert, "id" | "userId" | "createdAt" | "updatedAt">>) { const db = await getDb(); if (!db) return { persisted: false as const }; const existing = await getAtlasBriefPreferences(userId); if (existing) { await db.update(atlasBriefPreferences).set(values).where(and(eq(atlasBriefPreferences.id, existing.id), eq(atlasBriefPreferences.userId, userId))); return { persisted: true as const }; } await db.insert(atlasBriefPreferences).values({ userId, ...values }); return { persisted: true as const }; }
export async function updateAtlasBriefTask(userId: number, cadence: "daily" | "weekly", taskUid: string | null) { const db = await getDb(); if (!db) return false; const preferences = await getAtlasBriefPreferences(userId); if (!preferences) return false; const column = cadence === "daily" ? { dailyTaskUid: taskUid } : { weeklyTaskUid: taskUid }; await db.update(atlasBriefPreferences).set(column).where(and(eq(atlasBriefPreferences.id, preferences.id), eq(atlasBriefPreferences.userId, userId))); return true; }
export async function findAtlasBriefPreferenceByTask(taskUid: string) { const db = await getDb(); if (!db) return null; return (await db.select().from(atlasBriefPreferences).where(eq(atlasBriefPreferences.dailyTaskUid, taskUid)).limit(1))[0] ?? (await db.select().from(atlasBriefPreferences).where(eq(atlasBriefPreferences.weeklyTaskUid, taskUid)).limit(1))[0] ?? null; }
export async function createAtlasBriefRecord(userId: number, cadence: "daily" | "weekly", summary: string) { const db = await getDb(); if (!db) return false; await db.insert(atlasBriefRecords).values({ userId, cadence, summary }); return true; }
