import AsyncStorage from "@react-native-async-storage/async-storage";
import * as Notifications from "expo-notifications";
import { Platform } from "react-native";

const STORAGE_KEY = "atlas-brief-notification-ids-v1";
export type AtlasBriefNotificationPreferences = { dailyEnabled: boolean; dailyHour: number; dailyMinute: number; weeklyEnabled: boolean; weeklyWeekday: number; weeklyHour: number; weeklyMinute: number; notificationEnabled: boolean; digestMode: boolean };

Notifications.setNotificationHandler({ handleNotification: async () => ({ shouldPlaySound: false, shouldSetBadge: false, shouldShowBanner: true, shouldShowList: true }) });

async function clearAtlasBriefNotifications() { const raw = await AsyncStorage.getItem(STORAGE_KEY); const ids = raw ? (JSON.parse(raw) as string[]) : []; await Promise.all(ids.map((id) => Notifications.cancelScheduledNotificationAsync(id).catch(() => undefined))); await AsyncStorage.removeItem(STORAGE_KEY); }
export async function applyAtlasBriefNotifications(preferences: AtlasBriefNotificationPreferences) { if (Platform.OS === "web") return { status: "web_unsupported" as const }; await clearAtlasBriefNotifications(); if (!preferences.notificationEnabled) return { status: "disabled" as const }; if (Platform.OS === "android") await Notifications.setNotificationChannelAsync("atlas-briefs", { name: "Atlas briefs", importance: Notifications.AndroidImportance.DEFAULT, vibrationPattern: [0, 120], lightColor: "#1D6B54" }); const current = await Notifications.getPermissionsAsync(); const permission = current.status === "granted" ? current : await Notifications.requestPermissionsAsync(); if (permission.status !== "granted") return { status: "permission_denied" as const }; const ids: string[] = []; if (preferences.dailyEnabled) ids.push(await Notifications.scheduleNotificationAsync({ content: { title: "Your daily Atlas brief is ready", body: preferences.digestMode ? "Your next best step and important context are waiting." : "Open Atlas for your fresh personal briefing.", data: { url: "/(tabs)" }, }, trigger: { hour: preferences.dailyHour, minute: preferences.dailyMinute, repeats: true, channelId: "atlas-briefs" } as any })); if (preferences.weeklyEnabled) ids.push(await Notifications.scheduleNotificationAsync({ content: { title: "Your weekly Atlas review is ready", body: "Review outcomes, progress, and one considered next move.", data: { url: "/(tabs)/impact" }, }, trigger: { weekday: preferences.weeklyWeekday + 1, hour: preferences.weeklyHour, minute: preferences.weeklyMinute, repeats: true, channelId: "atlas-briefs" } as any })); await AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(ids)); return { status: "scheduled" as const, count: ids.length }; }
