import type { ActionCenterItem, GraphNode, PulseItem, ScenarioPlan, ScenarioResult } from "@/lib/atlas-life-model";

export function priorityScore(action: ActionCenterItem) { return Math.round(action.importance * 0.24 + action.urgency * 0.22 + action.expectedValue * 0.18 + action.riskReduction * 0.12 + action.goalAlignment * 0.16 + action.reversibility * 0.04 + action.confidence * 0.04 - Math.min(action.effort, 90) * 0.08); }
export function canEnableAutomation(action: ActionCenterItem, level: number) { return level === 4 && action.automationAllowed && action.domain !== "finance" && action.domain !== "health"; }
export function sortActions(actions: ActionCenterItem[]) { return [...actions].sort((a, b) => priorityScore(b) - priorityScore(a)); }
export function nextBestAction(actions: ActionCenterItem[]) { return sortActions(actions.filter((action) => action.state === "today"))[0]; }
export function sortPulse(items: PulseItem[]) { return [...items].filter((item) => !item.dismissed).sort((a, b) => (b.importance * 0.58 + b.urgency * 0.32 + b.confidence * 0.1) - (a.importance * 0.58 + a.urgency * 0.32 + a.confidence * 0.1)); }
export function resolveEntity(query: string, graph: GraphNode[]) { const normalized = query.toLowerCase(); return graph.find((node) => node.label.toLowerCase().includes(normalized) || node.summary.toLowerCase().includes(normalized)); }
function scenario(title: string, subtitle: string, monthlyChange: number, timeImpactHours: number, opportunity: string, risk: string, resilience: string): ScenarioResult { return { title, subtitle, monthlyChange, timeImpactHours, opportunity, risk, resilience, isEstimate: true }; }
export function buildSavingsScenario(monthlySavings: number, baselineSavings = 100): ScenarioPlan { const delta = monthlySavings - baselineSavings; return { id: `scenario-${monthlySavings}`, prompt: `What if I save €${monthlySavings} each month?`, currency: "EUR", createdAt: new Date().toISOString(), current: scenario("Current path", `Continue saving €${baselineSavings} monthly`, baselineSavings, 0, "Stable progress", "Moderate", "Buffer grows steadily"), bestCase: scenario("Best case", `Save €${monthlySavings} monthly and avoid a major surprise cost`, monthlySavings, 1, "Reach the buffer sooner", "Low", "More flexibility"), baseCase: scenario("Base case", `Sustain €${monthlySavings} monthly with one adjustment`, monthlySavings, 2, "Target remains on track", "Moderate", "Improving"), worstCase: scenario("Worst case", "An unexpected expense interrupts one month", Math.max(0, monthlySavings - Math.abs(delta || 25)), 4, "Target takes longer", "Higher", "Use a contingency plan") }; }
