import AsyncStorage from "@react-native-async-storage/async-storage";
import { createContext, useCallback, useContext, useEffect, useMemo, useState, type ReactNode } from "react";
import { buildSavingsScenario, nextBestAction, sortActions, sortPulse } from "@/lib/atlas-life-engine";
import { initialGraph, initialImpactRecords, initialLifeActions, initialMemories, initialPreference, initialPriceWatches, initialProductLifecycles, initialPulse, initialTrustRecords, type ActionCenterItem, type AutopilotLevel, type DomainEvent, type DomainEventType, type ImpactRecord, type MemoryRecord, type MemoryType, type OutcomeRating, type PreferenceProfile, type PriceWatch, type ProductLifecycle, type PulseItem, type ScenarioPlan, type TrustRecord } from "@/lib/atlas-life-model";

type LifeState = { memories: MemoryRecord[]; preference: PreferenceProfile; pulse: PulseItem[]; actions: ActionCenterItem[]; scenarios: ScenarioPlan[]; autopilotLevel: AutopilotLevel; graph: typeof initialGraph; trustRecords: TrustRecord[]; impactRecords: ImpactRecord[]; productLifecycles: ProductLifecycle[]; priceWatches: PriceWatch[]; events: DomainEvent[]; quietHours: boolean; digestMode: boolean };
type AtlasLifeContextValue = LifeState & { ready: boolean; prioritizedPulse: PulseItem[]; nextAction?: ActionCenterItem; orderedActions: ActionCenterItem[]; createMemory: (content: string, type: MemoryType) => void; updateMemory: (id: string, content: string) => void; deleteMemory: (id: string) => void; toggleMemory: (id: string) => void; exportMemories: () => string; dismissPulse: (id: string) => void; setAutopilotLevel: (level: AutopilotLevel) => void; updateAction: (id: string, state: ActionCenterItem["state"]) => void; recordOutcome: (id: string, rating: OutcomeRating, note?: string) => void; createScenario: (monthlySavings: number) => void; advanceProductLifecycle: (id: string, status: ProductLifecycle["status"]) => void; recordContribution: (type: string) => void; setAttentionControls: (values: { quietHours?: boolean; digestMode?: boolean }) => void; recordEvent: (type: DomainEventType, payload: DomainEvent["payload"]) => void; };
const STORAGE_KEY = "atlas-life-os-state-v2"; const initialState: LifeState = { memories: initialMemories, preference: initialPreference, pulse: initialPulse, actions: initialLifeActions, scenarios: [buildSavingsScenario(200)], autopilotLevel: 1, graph: initialGraph, trustRecords: initialTrustRecords, impactRecords: initialImpactRecords, productLifecycles: initialProductLifecycles, priceWatches: initialPriceWatches, events: [], quietHours: false, digestMode: true };
const AtlasLifeContext = createContext<AtlasLifeContextValue | undefined>(undefined);
export function AtlasLifeProvider({ children }: { children: ReactNode }) { const [state, setState] = useState<LifeState>(initialState); const [ready, setReady] = useState(false);
  useEffect(() => { AsyncStorage.getItem(STORAGE_KEY).then((saved) => { if (saved) setState((current) => ({ ...current, ...(JSON.parse(saved) as Partial<LifeState>) })); }).finally(() => setReady(true)); }, []);
  useEffect(() => { if (ready) AsyncStorage.setItem(STORAGE_KEY, JSON.stringify(state)); }, [ready, state]);
  const recordEvent = useCallback((type: DomainEventType, payload: DomainEvent["payload"]) => setState((current) => ({ ...current, events: [{ id: `${Date.now()}-${type}`, type, payload, occurredAt: new Date().toISOString() }, ...current.events].slice(0, 80) })), []);
  const createMemory = useCallback((content: string, type: MemoryType) => { const date = new Date().toISOString(); setState((current) => ({ ...current, memories: [{ id: `memory-${Date.now()}`, type, content: content.trim(), confidence: 1, source: "user", createdAt: date, updatedAt: date, userConfirmed: true, enabled: true }, ...current.memories] })); }, []);
  const updateMemory = useCallback((id: string, content: string) => setState((current) => ({ ...current, memories: current.memories.map((memory) => memory.id === id ? { ...memory, content, updatedAt: new Date().toISOString(), userConfirmed: true } : memory) })), []);
  const deleteMemory = useCallback((id: string) => setState((current) => ({ ...current, memories: current.memories.filter((memory) => memory.id !== id) })), []);
  const toggleMemory = useCallback((id: string) => setState((current) => ({ ...current, memories: current.memories.map((memory) => memory.id === id ? { ...memory, enabled: !memory.enabled } : memory) })), []);
  const dismissPulse = useCallback((id: string) => setState((current) => ({ ...current, pulse: current.pulse.map((item) => item.id === id ? { ...item, dismissed: true } : item) })), []);
  const setAutopilotLevel = useCallback((autopilotLevel: AutopilotLevel) => setState((current) => ({ ...current, autopilotLevel })), []);
  const updateAction = useCallback((id: string, actionState: ActionCenterItem["state"]) => { setState((current) => ({ ...current, actions: current.actions.map((action) => action.id === id ? { ...action, state: actionState } : action) })); recordEvent(actionState === "completed" ? "GoalCompleted" : actionState === "rejected" ? "RecommendationRejected" : "RecommendationAccepted", { actionId: id, state: actionState }); }, [recordEvent]);
  const recordOutcome = useCallback((id: string, outcome: OutcomeRating, outcomeNote?: string) => setState((current) => ({ ...current, actions: current.actions.map((action) => action.id === id ? { ...action, outcome, outcomeNote, state: "completed" } : action) })), []);
  const createScenario = useCallback((monthlySavings: number) => setState((current) => ({ ...current, scenarios: [buildSavingsScenario(monthlySavings), ...current.scenarios] })), []);
  const advanceProductLifecycle = useCallback((id: string, status: ProductLifecycle["status"]) => { setState((current) => ({ ...current, productLifecycles: current.productLifecycles.map((product) => product.id === id ? { ...product, status } : product) })); recordEvent("PurchaseCreated", { productId: id, lifecycle: status }); }, [recordEvent]);
  const recordContribution = useCallback((type: string) => { const createdAt = new Date().toISOString(); setState((current) => ({ ...current, impactRecords: [{ id: `impact-${Date.now()}`, level: "individual", type, quantity: 1, unit: "user-reported contribution", methodology: "User-confirmed Atlas contribution entry", evidence: "Recorded in Atlas", verification: "reported", confidence: 0.8, createdAt }, ...current.impactRecords] })); recordEvent("ImpactRecorded", { type, source: "user" }); }, [recordEvent]);
  const setAttentionControls = useCallback((values: { quietHours?: boolean; digestMode?: boolean }) => setState((current) => ({ ...current, ...values })), []);
  const value = useMemo<AtlasLifeContextValue>(() => ({ ...state, ready, prioritizedPulse: sortPulse(state.pulse), nextAction: nextBestAction(state.actions), orderedActions: sortActions(state.actions), createMemory, updateMemory, deleteMemory, toggleMemory, exportMemories: () => JSON.stringify(state.memories, null, 2), dismissPulse, setAutopilotLevel, updateAction, recordOutcome, createScenario, advanceProductLifecycle, recordContribution, setAttentionControls, recordEvent }), [advanceProductLifecycle, createMemory, deleteMemory, dismissPulse, ready, recordContribution, recordEvent, recordOutcome, setAttentionControls, setAutopilotLevel, state, toggleMemory, updateAction, updateMemory, createScenario]);
  return <AtlasLifeContext.Provider value={value}>{children}</AtlasLifeContext.Provider>;
}
export function useAtlasLife() { const context = useContext(AtlasLifeContext); if (!context) throw new Error("useAtlasLife must be used within AtlasLifeProvider"); return context; }
