import { FlatList, StyleSheet, Text, View } from "react-native";
import MaterialIcons from "@expo/vector-icons/MaterialIcons";
import { AppPressable, IconCircle, Pill } from "@/components/atlas-primitives";
import { ScreenContainer } from "@/components/screen-container";
import { atlasColors } from "@/constants/atlas";
import { opportunities } from "@/lib/atlas-data";
import { useAtlas } from "@/lib/atlas-context";
export default function DiscoverScreen() { const { addAction, openAI } = useAtlas(); return <ScreenContainer containerClassName="bg-background"><FlatList data={opportunities} keyExtractor={(item) => item.id} showsVerticalScrollIndicator={false} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.eyebrow}>DISCOVER</Text><Text style={styles.title}>Useful paths,{"\n"}not more noise.</Text><Text style={styles.intro}>Atlas prioritizes opportunities that fit your direction, resources, and values.</Text><View style={styles.filterRow}><Pill label="FOR YOU" tone="green" /><Pill label="OPPORTUNITIES" tone="outline" /><Pill label="LEARNING" tone="outline" /></View><View style={styles.contextCard}><IconCircle name="tune" tone="sun" /><View style={styles.contextCopy}><Text style={styles.contextTitle}>Your context is on</Text><Text style={styles.contextText}>Health, financial security, and career are shaping these matches.</Text></View></View><Text style={styles.sectionLabel}>MATCHED THIS WEEK</Text></>} renderItem={({ item, index }) => <AppPressable accessibilityLabel={`Add ${item.title} to your plan`} onPress={() => addAction(item.action, "Discover · tailored opportunity saved")} style={[styles.opportunityCard, index === opportunities.length - 1 && styles.lastCard]}><View style={styles.cardTop}><Text style={styles.cardEyebrow}>{item.eyebrow}</Text><MaterialIcons name="bookmark-add" size={20} color={atlasColors.green} /></View><Text style={styles.cardTitle}>{item.title}</Text><Text style={styles.cardDescription}>{item.description}</Text><View style={styles.cardFooter}><Text style={styles.cardAction}>{item.action}</Text><MaterialIcons name="arrow-forward" size={18} color={atlasColors.green} /></View></AppPressable>} ListFooterComponent={<AppPressable accessibilityLabel="Ask Atlas for matching opportunities" onPress={() => openAI("Find me opportunities for this skill.")} style={styles.askCard}><MaterialIcons name="auto-awesome" size={19} color={atlasColors.paper} /><Text style={styles.askText}>Ask Atlas to search with your context</Text><MaterialIcons name="arrow-forward" size={19} color={atlasColors.paper} /></AppPressable>} /></ScreenContainer>; }
const styles = StyleSheet.create({ content: { backgroundColor: atlasColors.mist, paddingBottom: 118, paddingHorizontal: 18, paddingTop: 18 }, eyebrow: { color: atlasColors.moss, fontSize: 10, fontWeight: "900", letterSpacing: 1.2 }, title: { color: atlasColors.ink, fontSize: 31, fontWeight: "800", letterSpacing: -1.1, lineHeight: 36, marginTop: 5 }, intro: { color: atlasColors.slate, fontSize: 15, lineHeight: 21, marginTop: 10, maxWidth: 340 }, filterRow: { flexDirection: "row", gap: 7, marginTop: 18 }, contextCard: { alignItems: "center", backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 18, borderWidth: 1, flexDirection: "row", gap: 11, marginTop: 20, padding: 12 }, contextCopy: { flex: 1, gap: 2 }, contextTitle: { color: atlasColors.ink, fontSize: 14, fontWeight: "800" }, contextText: { color: atlasColors.slate, fontSize: 11, lineHeight: 16 }, sectionLabel: { color: atlasColors.moss, fontSize: 10, fontWeight: "900", letterSpacing: 1.1, marginBottom: 10, marginTop: 25 }, opportunityCard: { backgroundColor: atlasColors.paper, borderColor: atlasColors.line, borderRadius: 21, borderWidth: 1, gap: 9, marginBottom: 11, padding: 16 }, lastCard: { marginBottom: 18 }, cardTop: { alignItems: "center", flexDirection: "row", justifyContent: "space-between" }, cardEyebrow: { color: atlasColors.green, fontSize: 10, fontWeight: "900", letterSpacing: 0.85 }, cardTitle: { color: atlasColors.ink, fontSize: 19, fontWeight: "800", letterSpacing: -0.35 }, cardDescription: { color: atlasColors.slate, fontSize: 13, lineHeight: 19 }, cardFooter: { alignItems: "center", flexDirection: "row", gap: 7, marginTop: 3 }, cardAction: { color: atlasColors.green, flex: 1, fontSize: 13, fontWeight: "800" }, askCard: { alignItems: "center", backgroundColor: atlasColors.greenDark, borderRadius: 18, flexDirection: "row", gap: 10, padding: 16 }, askText: { color: atlasColors.paper, flex: 1, fontSize: 14, fontWeight: "800" } });
